########################################################
MODULE:=nets
MODS := $(MODULE) utils arch layers serialize

SRCS := network network_load network_save loadsplitter network_level

########################################################
include ../Makefile.common

