########################################################
MODULE:=nets
MODS := $(MODULE) utils arch layers serialize

SRCS := network network_load network_save

########################################################
include ../Makefile.common

