########################################################
MODULE:=schedule
MODS := $(MODULE) utils layers nets serialize

########################################################
SRCS := layerlevel scheduler

########################################################
include ../Makefile.common

