#! /usr/bin/env  bash

set -x

yum_packages="python36 gcc-c++ libzip-devel zlib-static createrepo aws-cli unzip"
pip_packages="numpy pillow keras graphviz tensorflow==1.5 filelock boto3"


yum -y install $yum_packages
pip-3.6 install --user $pip_packages
