########################################################
MODULE:=memmgr
MODS := utils nets arch layers serialize

########################################################
SRCS := statebuffermgr

########################################################
include ../Makefile.common

