#!/usr/bin/env python3

# Copyright (C) 2017, Amazon.com. All Rights Reserved
#
# Mini runtime environment for SIM
#
# Example:

import argparse
import os.path
import sys
import re


print("\nINFO: started as  ", " ".join(sys.argv), flush=True)

InklingPath = os.environ.get('INKLING_PATH')

parser = argparse.ArgumentParser()
#TODO: define followign two args
parser.add_argument('--input_fmaps', help='',
                    dest="input_fmaps", default=[], nargs='+',)
parser.add_argument('--output_fmaps', help='',
                    dest="output_fmap", default=[], nargs=2)
parser.add_argument('--parallel_streams', help='run execution engines in parallel', action='store_true', default=False)
parser.add_argument('--tpb_dir', help='directory where tpb file(s) are located', default="./")
parser.add_argument('--inkling_debugflags', help='Inkling extra args', default=[], nargs='*')
args = parser.parse_args()
inputFmaps = args.input_fmaps
outputFmap = args.output_fmap
parallelStreams = args.parallel_streams
tpb_dir = args.tpb_dir
assert(len(inputFmaps) == 0) # embedded in tdb at the moment..
assert(len(outputFmap) == 0)


class RuntimeSim:
  def __init__(self):
    pass
  def run(self, inputFmaps, outputFmap):
    self.inputFmaps = inputFmaps
    self.outputFmap = outputFmap
    cmd = "PATH=%s/sim/:$PATH sim" % (InklingPath)
    if args.parallel_streams:
      cmd += " --angel %s/TrivNet-dma.tpb --sp %s/TrivNet-sp.tpb  --pe %s/TrivNet-pe.tpb --pool %s/TrivNet-pool.tpb --act %s/TrivNet-act.tpb" %(tpb_dir, tpb_dir, tpb_dir, tpb_dir, tpb_dir)
      sim_debug = os.environ.get('SIM_DEBUG')

      if sim_debug:
        if "all" in sim_debug:
          cmd += " --debugflags all"
        else:
          sim_engines = ["pe", "act", "pool", "tpb", "sync"]
          first = True
          for eng in sim_engines:
            if eng in sim_dbg:
              if first:
                first = False
                cmd += " --debugflags"
              cmd += " " + eng
    else:
      cmd += " %s/TrivNet.tpb" % (tpb_dir)
    if len(args.inkling_debugflags) != 0:
      cmd += " --debugflags %s" %  " ".join(args.inkling_debugflags)


    print("INFO: executing %s" % cmd, flush=True)
    ret = os.system(cmd)
    return ret


runtime = RuntimeSim()
ret = runtime.run(inputFmaps, outputFmap)

assert(ret == 0)
