#ifndef UARCH_CFG_H
#define UARCH_CFG_H

#define UNUSED(X) (void)(X)

#define SZ(BITS) (1 << (BITS))
#define ROW_BITS 7
#define COLUMN_BITS 6
#define BANK_BITS 13
#define ADDRESS_BITS 32
#define BANKS_PER_ROW_BITS 2
#define BANKS_PER_COLUMN_BITS 4
#define INSTRUCTION_NBYTES 256
#define SB_SIZE SZ(ROW_BITS + BANKS_PER_ROW_BITS + BANK_BITS)
#define ROW_SIZE SZ(BANK_BITS + BANKS_PER_ROW_BITS)
#define COLUMN_SIZE SZ(BANK_BITS + BANKS_PER_COLUMN_BITS)
#define MMAP_SB_BASE 0
#define MMAP_PSUM_BASE SB_SIZE

#endif

