#ifndef UARCH_CFG_H
#define UARCH_CFG_H

#define ROW_BITS 7
#define COLUMN_BITS 6
#define BANK_BITS 13
#define ADDRESS_BITS 32
#define BANKS_PER_PARTITION_BITS 2
#define INSTRUCTION_NBYTES 256
#define SB_SIZE (1 << ROW_BITS) * (1<<BANKS_PER_PARTITION_BITS) * ( 1 << BANK_BITS)
#define MMAP_PSUM_BASE SB_SIZE

#endif

