#!/bin/bash

if [ "$KAENA_PATH" = "" ] || [ "$BLD_DIR" = "" ]; then
    echo "Enviorment varaibles not set..."
    echo "Exiting" && exit 1
fi

KCC_INSTALL_DIR=${BLD_DIR}/tmp_install_kcc

# get release version
# this will get the most recent annotated tag from git, in the format of
# v{major}.{minor}.{build}
# the tag itself will be generated by the release process (on Jenkins)
cd $KAENA_PATH || exit 1
tag=$(git describe --abbrev=0)

# create installation files and directory
rm -rf $KCC_INSTALL_DIR
mkdir -p $KCC_INSTALL_DIR || exit 1
(cd $KAENA_PATH && make install PREFIX=$KCC_INSTALL_DIR) || exit 1

pack_dir=$1
if [ $# -eq 0 ]; then
   pack_dir=${KCC_BLD_DIR}
fi

# pack installation files into one file
mkdir -p ${pack_dir} || exit 1
cd ${KCC_INSTALL_DIR}
tar -pcvzf ${pack_dir}/kcc-${tag}.tar.gz bin lib

# clean the created directories
rm -rf $KCC_INSTALL_DIR
