########################################################
MODULE:=memmgr
MODS := utils nets arch layers serialize

########################################################
SRCS := statebufmgr

########################################################
include ../Makefile.common

