########################################################
MODULE:=serialize
MODS := $(MODULE) utils 

########################################################
SRCS := serlayer serwaveop serwaveop_load serwaveop_save

########################################################
include ../Makefile.common

