########################################################
MODULE:=serialize
MODS := $(MODULE) utils

########################################################
FILES := layer waveop waveop_load waveop_save
SRCS := $(addprefix ser,$(FILES))
########################################################

########################################################
include ../Makefile.common

