
########################################################
MODULE:=compisa
MODS := $(MODULE) utils wave

SRCS := \
	compisadmatrigger compisacommon


########################################################
include ../Makefile.common

