
########################################################
MODULE:=compisa
MODS := $(MODULE) utils wave

SRCS := \
	compisacommon


########################################################
include ../Makefile.common

