########################################################
MODULE:=codegen
MODS := $(MODULE) utils nets layers

FILES := layer datalayer inputlayer convlayer relulayer tanhlayer activlayer \
         poollayer maxpoollayer avgpoollayer constlayer biasaddlayer resaddlayer

SRCS := codegen $(addprefix $(MODULE),$(FILES))
########################################################

########################################################
include ../Makefile.common

