########################################################
MODULE:=codegen
MODS := $(MODULE) utils nets layers

########################################################
SRCS := codegenlayer codegeninputlayer codegenconvlayer codegenrelulayer codegentanhlayer codegenactivlayer codegenpoollayer codegenmaxpoollayer codegenavgpoollayer codegen

########################################################
include ../Makefile.common

