########################################################
MODULE:=codegen
MODS := $(MODULE) utils nets layers

########################################################
SRCS := codegenlayer \
codegendatalayer codegeninputlayer codegenconvlayer \
codegenrelulayer codegentanhlayer codegenactivlayer \
codegenpoollayer codegenmaxpoollayer codegenavgpoollayer \
codegenconstlayer codegenbiasaddlayer codegenresaddlayer \
codegen

########################################################
include ../Makefile.common

