#!/usr/bin/python

import sys
import re

# Convert jenkins URL to ssh sioptvpc URL to allow scp or rsync
# (Taken from RunAll)
def https2sshUrl(httpsUrl):
    sshUrl0 = re.sub('/(\d+)/artifact/', r'/builds/\1/archive/', httpsUrl)
    sshUrl1 = re.sub('https://siopt-294228977.us-east-1.elb.amazonaws.com/ci-server-tonga-sw/',
                    'siopt.vpc:/proj/jenkins/servers/tonga-sw/home/', sshUrl0)
    sshUrl = re.sub('view/[a-zA-Z0-9-_]+/', '', sshUrl1)
    sshUrl = re.sub('job/', 'jobs/', sshUrl)
    #if httpsUrl != sshUrl:
    #    print('INFO: translated {0} to {1}'.format(httpsUrl, sshUrl))
    #assert not 'https:' in sshUrl
    return sshUrl

if len(sys.argv) > 1:
    print(https2sshUrl(sys.argv[1]))
