#! /usr/bin/env bash

Error () {
    echo 1>&2 "$@"
}
Fatal () {
    Error "$@"
    exit 1
}

printAll=false

while let "$# != 0"
do
    case "x$1" in
    (x--int16|x-int16)                      TYPE=uint16 ;;
    (x--uint16|x-uint16)                    TYPE=uint16 ;;
    (x--int8|x-int8)                        TYPE=uint8 ;;
    (x--uint8|x-uint8)                      TYPE=uint8 ;;
    (x--float16|x--fp16|x-float16|x-fp16)   TYPE=float16 ;;
    (x--float32|x--fp32|x-float32|x-fp32)   TYPE=float32 ;;
    (x-all|x--all) printAll=true ;;

    (x-*) Fatal Wrong option $1 ;;
    (*)   break ;;
    esac
    shift
done

case "x$TYPE" in
(x) Fatal Need type size option: --int8, --uint8, --int16, --uint16, --float16 --float32
;;
esac
file=$1

q=''''
qq='"'

 
#python3_cmd =  'import numpy as np; x=np.load("' ^ $file ^ '"); print("Output OFMAP\n", x)'
#python3_cmd='import numpy as np; np.set_printoptions(threshold=np.nan); x=np.load("'${file}'"); print("FMAP", x.shape, "\n", x.view(dtype=np.'${TYPE}'))'

python3_cmdA='import numpy as np'
python3_cmdB='np.set_printoptions(edgeitems=10000000)'
python3_cmdC='x=np.load("'${file}'"); print("FMAP", x.shape, "\n", x.view(dtype=np.'${TYPE}'))'

if $printAll; then
    python3_cmd=$python3_cmdA';'$python3_cmdB';'$python3_cmdC
else
    python3_cmd=$python3_cmdA';'$python3_cmdC
fi


exec python3 -c "$python3_cmd"

