#!/usr/bin/env python3

import sys
import numpy as np
import argparse
import json
from keras.applications.imagenet_utils import preprocess_input, decode_predictions

print("\nINFO: started as  ", " ".join(sys.argv), flush=True)

parser = argparse.ArgumentParser()
parser.add_argument('--inputs', help='input image files',
                    dest="inputs", default=[], nargs='+')
parser.add_argument('--output', help='Output fmap npy file',
                    dest="output", default=None)


args = parser.parse_args()
assert(len(args.inputs) == 1)
ifmapFile = args.inputs[0]
assert(ifmapFile)

output = "rn50_classify_out.txt"
if args.output != None:
  output = args.output

print('Loading: ' + ifmapFile)
preds = np.load(ifmapFile)
d = decode_predictions(preds)
print('Predicted:', d)
result = ''
for t in d[0]:
    (l, label, prob) = t
    result += '%s, %.14f,' % (label, prob)
print(result)

with open(output, "w") as outf:
  print(result , file=outf)


