#!/usr/bin/env python3

import sys
import numpy as np
from PIL import Image
import argparse


print("\nINFO: started as  ", " ".join(sys.argv), flush=True)

parser = argparse.ArgumentParser()
parser.add_argument('--inputs', help='input image files',
                    dest="inputs", default=[], nargs='+')
parser.add_argument('--output', help='Output fmap npy file',
                    dest="output", default=None)

#TODO: add support


args = parser.parse_args()
assert(len(args.inputs) == 1)
imgFile = args.inputs[0]
assert(imgFile)
ifmapFile = args.output
assert(ifmapFile)

print('Loading: ' + imgFile)
img = Image.open(imgFile)
imgSized = img.resize((224, 224))
npArr = np.array(imgSized, dtype=np.float16)
fmap = npArr.reshape(1, 224, 224, 3)
#fmapNCHW = fmap.transpose(0, 3, 1, 2)
np.save(ifmapFile, fmap)
print('Wrote: '+ ifmapFile)


