#!/bin/sh
if [ $# -eq 0 ]; then
    x=0
else
    x=$1
fi
rm -f *-midout.npy
python3 $KAENA_PATH/compiler/me/me_main.py --kgraph compiler.json --wavegraph wavegraph.json --debug 3 --nname=generic --stop_after_layer_num $x --no_inter_layer_load 2>&1 | tee log-me.txt
