#!/usr/bin/env python3

# Copyright (C) 2018, Amazon.com. All Rights Reserved
#
# Kgraph visualization
#
import os, re
import tensorflow as tf


sess = tf.Session()
print("TF version", tf.__version__)

def getCudnnVersion():
  pid = os.getpid()
  cudaVersion, cudnnVersion = -1, -1
  for root, dirs, files in os.walk("/proc/%d/map_files" % pid):
    #print("ROOT %s DIRS %s FILES %s" % (root, dirs, files))
    for f in files:
      link = "%s/%s" % (root, f)
      path = os.path.realpath(link)
      #path = "/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.3"
      match = re.search(r'\/cuda-([\d\.]+)\/lib64\/libcudnn\.so\.([\d\.]+)', path)
      #print("DEBUG", path)
      if match:
        #print(path)
        cudaVersion, cudnnVersion = match.groups()
  return cudaVersion, cudnnVersion

cudaVersion, cudnnVersion = getCudnnVersion()
print("CUDA  version", cudaVersion)
print("CUDNN version", cudnnVersion)

