#!/usr/bin/env python3

import numpy as np
import os

b = 1
s = 1
for i in [0.02, 0.2]:
  for w in [0.01, 0.1]:
    for m in [1, 4, 64]:
      for c in [1, 4, 64]:
        for r in [1, 3]:
          for h in [3, 8, 16, 32]:
            conf = "b%d-h%d-r%d-s%d-c%d-m%d-" % (b, h, r, s, c, m) +  "wmin%g-wmax%g-imin%g-imax%g" % (-w, w, -i, i)
            cmd = '/bin/rm input.npy output.npy; make -f $KAENA_PATH/compiler/tffe/Makefile jdr_v2 NN_CONFIG=%s OUT_PREFIX=trivnet_ NN_NAME=1conv' % (conf)
            print("\n", cmd)
            os.system(cmd)

