#!/usr/bin/env python3

# Generator of neural networks for unit testing of Kaena compiler flow
# Variables - match teh TPB spec
#  h - image heights (and width)
#  c - channels - number of IFMAPs
#  m - outputs - number of OFMAPs
#  b - batch
#  s - stride
#  r - filter (height and width)
#  w - weight value range bound
#  i - input image value range bound


import numpy as np
import os

def testOk(h, r, s):  ## h=image size, r=filter size, s=stride
    if r > h:
        return False
    if s > h:
        return False

    return True


if 0:

  # Basic sweep from October 2017
  b = 1
  s = 1
  id = 0
  for i in [0.02, 0.2]:
    for w in [0.01, 0.1]:
      for m in [1, 4, 64]:
        for c in [1, 4, 64]:
          for r in [1, 3]:
            for h in [3, 8, 16, 32]:
              id += 1
              conf = "b%d-h%d-r%d-s%d-c%d-m%d-" % (b, h, r, s, c, m) +  "wmin%g-wmax%g-imin%g-imax%g" % (-w, w, -i, i)
              dir = "s%04d_%s" % (id, conf)
              cmd = 'mkdir %s; cd %s && ' % (dir, dir)
              cmd += 'make -f $KAENA_PATH/compiler/tffe/test/Makefile trivnet_conv1 NN_CONFIG=%s OUT_PREFIX=trivnet_ NN_NAME=1conv &&' % (conf)
              cmd += 'bash $KAENA_PATH/compiler/be/test/RunOne.sh *tgz > log-be.txt 2>&1 && '
              cmd += 'echo -n PASS || echo -n FAIL; echo "  "' + dir
              print("\n", cmd)
              os.system(cmd)
              #exit(1)

elif 1:

  # Custom sweep Jan 2018 - for Drazen padding+striding debug
  b = 1
  i = 0.2
  w = 0.1
  m = 1
  c = 1
  
  id = 0
  for s in [1, 2, 3, 4, 8]:
    for r in [1, 2, 3, 4, 5, 7]:
      for h in [2, 3, 4, 5, 6, 7, 14]:
        if not testOk(h, r, s):
          continue
        id += 1
        conf = "b%d-h%d-r%d-s%d-c%d-m%d-" % (b, h, r, s, c, m) +  "wmin%g-wmax%g-imin%g-imax%g" % (-w, w, -i, i)
        dir = "s%04d_%s" % (id, conf)
        cmd = 'mkdir %s; cd %s && ' % (dir, dir)
        cmd += 'make -f $KAENA_PATH/compiler/tffe/test/Makefile trivnet_conv1 NN_CONFIG=%s OUT_PREFIX=trivnet_ NN_NAME=1conv > log-fe.txt 2>&1 &&' % (conf)
        cmd += 'bash $KAENA_PATH/compiler/be/test/RunOne.sh *tgz > log-be.txt 2>&1 && '
        cmd += 'echo -n PASS || echo -n FAIL; echo "  "' + dir
        print("\n", cmd)
        os.system(cmd)
        #exit(1)
