########################################################
MODULE:=kelf
MODS := $(MODULE) utils nets layers wave

########################################################
FILES := dmadescription dmablock

SRCS := $(addprefix $(MODULE),$(FILES))

########################################################
include ../Makefile.common

