########################################################
MODULE:=utils
MODS := $(MODULE) nets layers serialize schedule

########################################################
SRCS := fmapdesc debug datatype printers types
## consts

########################################################
include ../Makefile.common

