#!/usr/bin/env python3

import os

tests = {
  "t0001" : [ "jdr_v2", "b1-h1-r1-s1-c1-m1-wmin2-wmax2-imin3-imax3", "1conv"],
  "t0002" : [ "jdr_v3", "b1-h1-r1-s1-c1-m1-wmin2-wmax3-imin5-imax5", "1conv"],
  "t0003" : [ "jdr_v3", "b1-Zh1-r1-s1-c1-m1-wmin2-wmax3-imin5-imax5", "I_ALWAYS_FAIL"],
  "t0010" : [ "jdr_v2", "b1-h16-r7-s1-c64-m64-wmin-0.1-wmax0.1-imin-0.2-imax0.2", "1conv"],
  "t0011" : [ "jdr_v2", "b1-h16-r9-s1-c64-m64-wmin-0.1-wmax0.1-imin-0.2-imax0.2", "1conv"],
  "t0012" : [ "jdr_v2", "b1-h35-r3-s1-c1-m1-wmin-0.1-wmax0.1-imin-0.2-imax0.2", "1conv"]
}

for testName in sorted(tests):
  (nnStruct, nnConfig, nnLabel) = tests[testName]
  cmd = 'mkdir %s && cd %s && make -f $KAENA_PATH/compiler/tffe/Makefile %s NN_CONFIG=%s OUT_PREFIX=trivnet_ NN_NAME=%s > log 2>&1; date; test -f *.tgz && echo PASS || echo FAIL' % (testName, testName, nnStruct, nnConfig, nnLabel)
  print("\nExecuting ", cmd)
  os.system(cmd)
  
