########################################################
MODULE=codegen
MODS = $(MODULE) utils nets layers

########################################################
SRCS = codegenlayer codegeninputlayer codegenconvlayer codegenrelulayer codegentanhlayer codegenactivlayer codegen

########################################################
include ../Makefile.common

