#ifndef _TYPES_H
#define _TYPES_H

#include <stdint.h>

enum ARBPRECTYPE {INVALID_ARBPRECTYPE=-1, UINT8=0, UINT32, FP32, NUM_ARBPRECTYPE};

enum ADDRCLASS    {INVALID_ADDRCLASS=-1, WEIGHT_ADDR=0, IFMAP_ADDR, PSUM_ADDR, NUM_ADDRCLASS};

enum ACTIVATIONFUNCTION {INVALID_ACTIVATIONFUNCTION=-1, RELU, LEAKY_RELU, SIGMIOD, TANH, IDENTITY, NUM_ACTIVATIONFUNCTION};

enum POOLTYPE {INVALID_POOLTYPE=-1, AVG_POOL, MAX_POOL, NO_POOL, NUM_POOLTYPE};


typedef uint64_t addr_t;
#define MAX_ADDR UINTMAX_MAX

typedef uint64_t tick_t;
#define MAX_TICK UINTMAX_MAX

#endif
