########################################################
MODULE:=wavecode
MODS := $(MODULE) utils nets layers wave

########################################################
SRCS := wavecode \
wavecodewaveop \
wavecodesbatomfile \
wavecodesbatomsave \
wavecodematmul \
wavecodepool

########################################################
include ../Makefile.common

