########################################################
MODULE:=layers
MODS := $(MODULE) utils nets serialize

SRCS := layer  \
activlayer relulayer tanhlayer  \
combinelayer subsamplelayer convlayer \
constlayer inputlayer \
resaddlayer biasaddlayer \
poollayer maxpoollayer avgpoollayer \

########################################################
include ../Makefile.common

