########################################################
MODULE:=wave
MODS := $(MODULE) utils nets serialize

SRCS := waveop  \
matmulwaveop \
sbatomwaveop \
sbatomfilewaveop \
sbatomsavewaveop

########################################################
include ../Makefile.common

