########################################################
MODULE:=wave
MODS := $(MODULE) utils nets serialize

SRCS := waveop   \
matmulwaveop     \
sbatomwaveop     \
sbatomfilewaveop \
sbatomsavewaveop \
poolwaveop       \
activationwaveop \
resaddwaveop

########################################################
include ../Makefile.common

