########################################################
MODULE:=events
MODS := $(MODULE) utils wave

SRCS := eventmgr   \
event

########################################################
include ../Makefile.common

