########################################################
MODULE:=events
MODS := $(MODULE) utils wave

SRCS := \
	events \
	eventmgr


########################################################
include ../Makefile.common

